version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: tfpacker
    main: ./main.go
    binary: tfpacker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/jackchuka/tfpacker/internal/version.Version={{.Version}}
      - -X github.com/jackchuka/tfpacker/internal/version.Commit={{.Commit}}
      - -X github.com/jackchuka/tfpacker/internal/version.Date={{.Date}}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
